### ISSUE TITLE
Better function-name information

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/dbg-macro#12]
We currently use `__func__` to add the function name annotation in the output. However, the output for class methods or lambdas is not optimal:
``` c++
class user_defined_class {
 public:
  void some_method(int x) {
    dbg(x);
  }
};

// ...

user_defined_class{}.some_method(42);

[](int x) {
  dbg("called from within a lambda!");
  return x;
}(42);
```
prints:
```
[..acro/tests/tests.cpp:34 (some_method)] x = 42 (int)
[..acro/tests/tests.cpp:138 (operator())] called from within a lambda!
```

If we would use `__PRETTY_FUNCTION__` instead, we could potentially turn `some_method` into `user_defined_class::some_method` and `operator()` into `main()::<lambda(int)>`. This would, however, require us to post-process the `__PRETTY_FUNCTION__` string and remove return type, argument names, etc.

See also: https://stackoverflow.com/a/29856690/704831

**Comment by hmenke** [comment]
Why not use `__PRETTY_FUNCTION__` as a whole?  This way you get the most info: return type, arguments, and template arguments.  This might be useful to distinguish overloads.  On the other hand it would take a lot of screen space.

**Comment by sharkdp** [comment]
> On the other hand it would take a lot of screen space.

Yes, exactly. That's why I was thinking about stripping that information.

**Comment by sharkdp** [comment]
I think parsing the `__PRETTY_FUNCTION__` is probably not a good idea. There are too many edge cases (e.g. https://stackoverflow.com/questions/29777059/pretty-function-can-a-return-type-contain-parentheses)

**Comment by sharkdp** [comment]
I think I'm okay with the current situation. Let's close this for now.
