### ISSUE TITLE
Support always on colors

### ISSUE THREAD

**Issue by dufferzafar** [sharkdp/dbg-macro#120]
I'm using `dbg()` in a test that runs via `ctest` which prevents any colors from appearing - as ctest buffers stdout so it has the option of not showing any output if the tests passed.

Running the test binary without `ctest` gives proper colors.

Having a way to enable coloring regardless of `isatty` would be great. Something like `#DBG_MACRO_COLOR_ALWAYS` (akin to `grep --color=always`).

**Comment by thecaralice** [comment]
Related to #105

**Comment by sharkdp** [comment]
Sounds like a good idea!

> Something like `#DBG_MACRO_COLOR_ALWAYS` (akin to `grep --color=always`).

:+1:
