### ISSUE TITLE
How to force print the full content, not the one with ellipsis

### ISSUE THREAD

**Issue by hhhxiao** [sharkdp/dbg-macro#124]
How can i print all the full content of a variable such as the follows:
```
[.\xxx.cpp:19 (xxfunction)] tree = {1, 2, 4, 5, 3, 6, -1, -1, -1, -1, -1, -1, -1,size:13} (std::vector<int>)
```
or not:
```
[.\xxx.cpp:19 (xxfunction)] tree = {1, 2, 4, 5, 3, 6, -1, -1, -1, -1, ... size:13} (std::vector<int>)
```
Is there a macro to set it up?

**Comment by nocoinman** [comment]
@hhhxiao For printing size of container [is clipped](https://github.com/sharkdp/dbg-macro/blob/4db61805d90cb66d91bcc56c2703591a0127ed11/dbg.h#L704). You could either increase the size from `10` to a desirable value or remove the clipping logic altogether forcing to print container entirely although this could lead to a messy output

**Comment by hhhxiao** [comment]
Thank you very much for your answer, so the current solution is that I have to manually modify the source code

**Comment by sharkdp** [comment]
As @nocoinman said, this is currently not possible. And I don't plan to add a new feature to allow for this, unless someone has a really elegant proposal on how to integrate this.
