### ISSUE TITLE
Some enhancement proposals for CMake based usecases

### ISSUE THREAD

**Issue by winwinashwin** [sharkdp/dbg-macro#135]
1. Currently we only support making `dbg(...)` no-op with `DBG_MACRO_DISABLE`. When using with CMake it is more intuitive to make it no-op when CMake is invoked in Release mode.
2. Following the [instructions from README](https://github.com/sharkdp/dbg-macro?tab=readme-ov-file#with-cmake), the dbg statements looks like this
```
[..m/mines/src/grid.cpp:103 (reset)] _state = 0 (Grid::State)
```
The source file path could be cleaned up.

**Comment by sharkdp** [comment]
> Currently we only support making `dbg(...)` no-op with `DBG_MACRO_DISABLE`. When using with CMake it is more intuitive to make it no-op when CMake is invoked in Release mode.

Having the macro active in release mode is a deliberate design choice. See https://doc.rust-lang.org/std/macro.dbg.html for reasoning.

> The source file path could be cleaned up.

If you have any ideas on how, please let us know. I wanted to shorten it to make the main content readable.

I'm closing this for now, but let me know if there is anything you think we should do.
