### ISSUE TITLE
Reverse typedefs

### ISSUE THREAD

**Issue by thejohnfreeman** [sharkdp/dbg-macro#16]
Branching off #5 that added type information, some of the types are not very pretty, e.g. `std::__cxx11::basic_string<char>` when most people would like to see `std::string`. It would be nice to be able to define "reverse typedefs" that transform fully-qualified underlying type names into pretty type aliases, and to include batteries for some of the most common instances, e.g. `std::string` and `std::vector`.

**Comment by sharkdp** [comment]
the "reverse typedefs" would hopefully just be specializations of the `type_name<…>()` function. I have added one for `std::string` in #17. Unfortunately, it's not that straightforward for `std::vector<T>`.

**Comment by sharkdp** [comment]
Closed via #20 by @hmenke
