### ISSUE TITLE
Add support for std::nullptr_t

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/dbg-macro#18]

**Comment by hmenke** [comment]
Isn't that already covered by this?
https://github.com/sharkdp/dbg-macro/blob/f4e91b6bc3a30746551cb45ee02be8aacac7e2e5/dbg.h#L163-L171
Or do you want `dbg(nullptr)` to behave differently? I think the `nullptr` literal is the only thing of type `std::nullptr_t`.

**Comment by sharkdp** [comment]
currently, `dbg(nullptr)` simply fails to compile (because it is of type `std::nullptr_t` and not P*`).

> I think the nullptr literal is the only thing of type std::nullptr_t.

If calling with the actual `nullptr` literal is the only way to trigger this, we don't really need to add support - you are right.
