### ISSUE TITLE
Support for enums?

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/dbg-macro#21]
Enums are currently not supported (unless the user has defined an `operator<<` overload for `ostream`).

We could potentially implement support for enums if we:
- use `std::is_enum<E>` to add a specialization for enums (similar to containers)
- cast the value to `std::underlying_type<E>::type` and print that.

If we decide to do this, we should probably only use the overload if *no* custom `operator<<` is defined for that type.

**Comment by hmenke** [comment]
https://github.com/quicknir/wise_enum
https://www.youtube.com/watch?v=GCkhcT2oxCA

**Comment by sharkdp** [comment]
Ok, but that would require modifications in the user code, right?

I don't think we could use `WISE_ENUM_ADAPT` to generate the necessary code, for a user enum type `CustomeEnum`, given just an invocation of `dbg(CustomEnum::VALUE1)`.

**Comment by gggin** [comment]
https://github.com/Neargye/magic_enum

**Comment by sharkdp** [comment]
> https://github.com/Neargye/magic_enum

Thank you for the reference. Unfortunately, it does require C++17 and we are targeting C++11.
