### ISSUE TITLE
Log to user-defined stream (instead of std::cerr)

### ISSUE THREAD

**Issue by gggin** [sharkdp/dbg-macro#25]
usually logging library support android.

**Comment by sharkdp** [comment]
This is not a logging library.

What exactly do you mean by "android support"?

**Comment by gggin** [comment]
if you made a choice for no android support , you should provider a interface for replace std::err << to something else to support android output interface like  so I can write my own  `__android_log_print` wrapper.

something like this:
https://stackoverflow.com/questions/12152555/how-to-print-log-in-android-c-file

**Comment by xorz57** [comment]
But it is really not a logging library as @sharkdp said, I don't see why it would be practical to use in android.

**Comment by gggin** [comment]
@xorz57 cpp library should be run on any platform that support c++, If cannot or featureless, maybe provide something extension to extend the library.

**Comment by xorz57** [comment]
@gggin fair enough!

**Comment by sharkdp** [comment]
@gggin If I understand you correctly, you would like to use the core-functionality of this library without having to rely on `std::cerr` to be availble? Sounds like a reasonable request for me.

**Comment by gggin** [comment]
Yes.  @sharkdp  maybe Template specialization， or a setter for a lambda or otherthings。

**Comment by ShikChen** [comment]
FWIW, the similar libs in [Go](https://github.com/y0ssar1an/q) and [Python](https://github.com/zestyping/q) also logs to `/tmp/q` so it's easier to inspect on complex systems. It's useful when the program

1. logs to some file and does not have stderr, or
2. already have too much logs in stderr

It's more like a choice about how quick-and-dirty dbg-macro would like to be though.

**Comment by sharkdp** [comment]
> similar libs in [Go](https://github.com/y0ssar1an/q) and [Python](https://github.com/zestyping/q) also logs to `/tmp/q` so it's easier to inspect on complex systems

That's actually a pretty cool idea! Should be in a separate ticket, maybe?

**Comment by sharkdp** [comment]
As for `/tmp/q`, I think that would work fine as long as you are running just a single process that writes to `/tmp/q`. As soon as multiple programs are running ("complex systems", as stated in your comment), that would not work at all. So we would probably have to add the PID and write to `/tmp/q.$PID` or similar. That immediately makes this less useful.

As for writing to something else then `std::cerr`: I would like to avoid adding more configuration options for now. I'm trying to design this library such that users only `#include <dbg.h>` and then immediately start putting `dbg(…)` in their code. Without any other compile- or runtime configuration.
