### ISSUE TITLE
Add a flag to enable or disable dbg for release builds.

### ISSUE THREAD

**Issue by Jackojc** [sharkdp/dbg-macro#26]
Not sure if there's currently a way to set a flag to enable or disable dbg depending on whether or not it's a debug build. If there is a flag, it should probably be documented, if not, maybe some kind of #define to effectively make the dbg macro do nothing.

**Comment by sharkdp** [comment]
> Not sure if there's currently a way to set a flag to enable or disable dbg depending on whether or not it's a debug build

There is no flag or mechanism to do this.

I'm trying to follow a similar philosophy as the Rust team did with their `dbg!(…)` macro.

Quoting from https://doc.rust-lang.org/std/macro.dbg.html

> The dbg! macro works exactly the same in release builds. This is useful when debugging issues that only occur in release builds or when debugging in release mode is significantly faster.

> Note that the macro is intended as a debugging tool and therefore you should avoid having uses of it in version control for longer periods.

This is why the `dbg(…)` macro does not disable itself in non-`DEBUG` builds.

That being said, I think I would be okay with adding a compile flag to disable the macro completely.

**Comment by sharkdp** [comment]
I have hadded a `DBG_MACRO_DISABLE` compile time flag that can be used to disable the macro.

If disabled, the macro can still be used in expressions since we define it to be `dbg(x) = x`.

**Comment by fgallegosalido** [comment]
That's okay. Anyway, you should add something to the the macro when it is disabled, because a lot of "-Wunused-value" warnings appear in g++ and clang++, but that's different issue

**Comment by xorz57** [comment]
@fgallegosalido I have prepared CI for AppleClang, GCC and MSVC. We will see about those warnings.

**Comment by sharkdp** [comment]
> Anyway, you should add something to the the macro when it is disabled, because a lot of "-Wunused-value" warnings appear in g++ and clang++

Good point. Would you like to open a new issue for that?

**Comment by fgallegosalido** [comment]
Okay, I'm opening it now

**Comment by Jackojc** [comment]
I think you're mixing this project up with the Rust macro of the same name (I believe this project was inspired by it). https://doc.rust-lang.org/std/macro.dbg.html
