### ISSUE TITLE
Build Fails on MSVC

### ISSUE THREAD

**Issue by xorz57** [sharkdp/dbg-macro#27]
![image](https://user-images.githubusercontent.com/1548352/59958068-741dba80-94a9-11e9-80b7-708812f78b36.png)

I would like to take this issue.

**Comment by xorz57** [comment]
OK, it looks like you are also using `unistd.h`. I can make it cross compatible as well!

**Comment by sharkdp** [comment]
Thank you for the feedback!

I had never tested in on MSVC, so I'm not really surprised it doesn't work :-). If you would like to work on MSVC support, that would be great! Ideally, we would also set up Travis to run a build on Windows/MSVC.

> At first I thought the compiler flags are the only problem.

> It looks like you are also using `unistd.h`.

Yes, it is used for `isatty(…)`, to check whether or not STDERR is connected to an interactive terminal (or a pipe). Colors are done via ANSI escape sequences, but they should work just fine on Windows 10 / Powershell. I'd rather not try to use anything else for colorization.

But we can certainly make the `isatty(…)` check cross-platform.

**Comment by sharkdp** [comment]
see #29

**Comment by xorz57** [comment]
I made a pull request #31

**Comment by sharkdp** [comment]
I managed to make it compile & run (most of) the tests on MSVC in my original PR: #29

**Comment by sharkdp** [comment]
dbg macro should nie work on Windows
