### ISSUE TITLE
Many "-Wunused-value" warnings when DBG_MACRO_DISABLE is defined

### ISSUE THREAD

**Issue by fgallegosalido** [sharkdp/dbg-macro#36]
When we use `dbg()` with a variable, the compilers detect an unused value, so a warning is shown. This warnings should be hidden with pragmas or some language specific syntax.

**Comment by fgallegosalido** [comment]
I have a hack that can do the trick;

```
namespace dbg_macro{
    template <typename T>
    T unused_(T&& t){
        return t;
    }
}
#define dbg(...) dbg_macro::unused_(__VA_ARGS__)
```

That can do the job, but adds some boilerplate and it's not fully tested

**Comment by Jackojc** [comment]
Just out of curiosity, could you show some example code that produces a warning?

**Comment by fgallegosalido** [comment]
Take the `example.cpp` file and add at the beginning `#define DBG_MACRO_DISABLE`

**Comment by sharkdp** [comment]
@fgallegosalido Thank you! I took the liberty to implement your solution in #46.
