### ISSUE TITLE
Idea: add type information?

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/dbg-macro#5]
We could potentially use `typeid(…).name()` to add type information about the debugged value. This could be really helpful if used somewhere inside expressions where the type is not completely obvious.

We would have to find a cross-compiler way to demangle the `typeid(…).name()` string...

**Comment by hmenke** [comment]
You can determine the type as seen by the compiler at compile time using `__PRETTY_FUNCTION__` (available in Clang and GCC).
```cpp
#include <iostream>

template <typename T>
std::string print_type() {
    std::string type = __PRETTY_FUNCTION__;
    // -1 because null terminator counts into sizeof
    size_t prefixlen = sizeof("std::__cxx11::string print_type() [with T = ") - 1;
    size_t postfixlen = sizeof("; std::__cxx11::string = std::__cxx11::basic_string<char>]") - 1;
    return type.substr(prefixlen, type.size() - prefixlen - postfixlen);
}

int main() {
    int i = 1;
    std::cout << print_type<decltype(i)>() << '\n';
}
```
Somebody has also packaged this into something more robust and portable which also works in MSVC: https://github.com/Manu343726/ctti

**Comment by sharkdp** [comment]
Thank you very much, that's a cool trick!

There is also `boost::core::demangle(…)`, which I have used in the past. It seems to use something similar as [this stackoverflow post](https://stackoverflow.com/a/4541470/704831), namely `abi::__cxa_demangle` from `<cxxabi.h>`. It relies on the mangled name from `typeid(…).name()`, so it's not available at compile time. But that's not really needed for the `dbg(…)` macro.

> Somebody has also packaged this into something more robust and portable which also works in MSVC: https://github.com/Manu343726/ctti

That looks like an awesome library. On the other hand, I'd really like this project to be just a single header file. This means I would have to literally copy & paste code (+ license information) from that library to `dbg.h`...

**Comment by hmenke** [comment]
I think Jonathan "foonathan" Müller invented this trick.

> This means I would have to literally copy & paste code

That depends on how much you really need.  I'm pretty sure you can get away with https://github.com/Manu343726/ctti/blob/master/include/ctti/detail/pretty_function.hpp with some customizations.

**Comment by sharkdp** [comment]
> The clear downside of `typeid(…).name()` is that it gives you the representation of the type name as known to the runtime, which might not be human readable. Some implementations just report `i` for `int`.

Yes, but `demangle(…)` turns `i` into `int`.

> That depends on how much you really need. I'm pretty sure you can get away with https://github.com/Manu343726/ctti/blob/master/include/ctti/detail/pretty_function.hpp with some customizations.

yes, I guess we would need the compiler-agnostic version of `__PRETTY_FUNCTION__` from `detail/pretty_function.hpp` and the actual implementation of `nameof` (https://github.com/Manu343726/ctti/blob/master/include/ctti/nameof.hpp). They use their own string class, so we would probably replace this by `std::string`, if possible.

**Comment by hmenke** [comment]
The whole `nameof` business is only to make it `constexpr`.  I just tested it with GCC, Clang, and MSVC on rextester.com and the following works:
```cpp
#include <iostream>
#include <string>

template <typename T>
const char * print_type_impl() {
#if defined(__clang__)
    return __PRETTY_FUNCTION__;
#elif defined(__GNUC__) && !defined(__clang__)
    return __PRETTY_FUNCTION__;
#elif defined(_MSC_VER)
    return __FUNCSIG__;
#else
    #error "No support for this compiler."
#endif
}

template <typename T>
std::string print_type() {
#if defined(__clang__)
    size_t prefixlen = sizeof("const char *print_type_impl() [T = ") - 1;
    size_t suffixlen = sizeof("]") - 1;
#elif defined(__GNUC__) && !defined(__clang__)
    size_t prefixlen = sizeof("const char *print_type_impl() [T = ") - 1;
    size_t suffixlen = sizeof("]") - 1;
#elif defined(_MSC_VER)
    size_t prefixlen = sizeof("const char *__cdecl print_type_impl<") - 1;
    size_t suffixlen = sizeof(">(void)") - 1;
#else
    #error "No support for this compiler."
#endif
    std::string type = print_type_impl<T>();
    return type.substr(prefixlen, type.size() - prefixlen - suffixlen);
}

int main() {
    int i = 1;
    std::cout << print_type<decltype(i)>() << '\n';
}
```

**Comment by thejohnfreeman** [comment]
Do you need to update the example in the README? I was just about to request this feature, so `std::__cxx11::basic_string<char>` could be presented as `std::string`. Does your change accomplish that?

**Comment by sharkdp** [comment]
> Do you need to update the example in the README?

No, the macro currently outputs
```
std::__cxx11::basic_string<char>
```
for both gcc 8.3 and clang 8.0.

>  I was just about to request this feature, so `std::__cxx11::basic_string<char>` could be presented as `std::string`.

That sounds great.. but how many specializations would we need to add? For example, clang also outputs `std::vector<int, std::allocator<int> >` while gcc prints `std::vector<int>`.

**Comment by thejohnfreeman** [comment]
How many specializations? I don't know, but a few of the most popular ones and a way to add more would be great, in my opinion.

**Comment by sharkdp** [comment]
> How many specializations? I don't know, but a few of the most popular ones and a way to add more would be great, in my opinion.

Ok, agreed. Sounds like a good idea! Would you like to open a new ticket for that?
