### ISSUE TITLE
Add support for empty "dbg()" calls.

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/dbg-macro#64]
The `dbg-macro` call includes file, line and function information anyway, so empty
```c++
dbg();
```
calls can be helpful as well (instead of a dummy `dbg("this is executed")` call).

**Comment by DerekCresswell** [comment]
Hello. This seems like something suitable for someone new to this repo. I'd be happy to take this on as a stepping stone. :) Want to assign it to me?

**Comment by sharkdp** [comment]
Sure, sounds great!

**Comment by DerekCresswell** [comment]
@sharkdp It seems to be basically impossible to have array initialisation AND multiple arguments.   
Because the preprocessor just sees the commas as new arguments we can't have this work with more than one argument.   
What does work :  
`std::vector<int> arr = {1,0}; dbg(arr);`   
`dbg((std::vector<int>{0,1}));` (Though it does print the extra brackets)   

Simply because this uses macros I don't think if we can get around this.  
Seeing as it is still possible to do print the args is it worth the sacrifice?

**Comment by sharkdp** [comment]
> @sharkdp It seems to be basically impossible to have array initialisation AND multiple arguments (#2 ).
> Because the preprocessor just sees the commas as new arguments we can't have this work with more than one argument.

I think you are right. There is a similar limitation in `gtest` (see e.g. https://stackoverflow.com/q/44459921/704831, https://github.com/google/googletest/issues/634, https://github.com/google/googletest/issues/219, https://github.com/google/googletest/issues/733).

It's not just initializer lists, but also comma-separated template arguments (`Foo<int, 10>`) or unparenthesized comma-operators within lambda functions.

> Simply because this uses macros I don't think if we can get around this.

I also think so.

>  Seeing as it is still possible to do these do you think is it worth the sacrifice?

I believe I would rather give up multiple-argument support. I will close #2 and refer to this thread.

How do we proceed with this PR? Do you think that we should still implement the empty-argument macro call?

**Comment by DerekCresswell** [comment]
@sharkdp #67 can be pulled. The empty calls have no issue with any commas.   
Sad that comma seperated args has fallen away. At least we can have these.   

Though at the current moment seems like the tests don't like my most recent commit.

**Comment by sharkdp** [comment]
Closing for now, as we now support multiple arguments (#2). Empty calls can not be supported, unfortunately.
