### ISSUE TITLE
Document dbg_macro::prettyPrint in README (if it's still there)

### ISSUE THREAD

**Issue by alexeyr** [sharkdp/dbg-macro#96]
I found [a Reddit comment](https://www.reddit.com/r/cpp/comments/c2ysa7/a_dbg_macro_for_c/ernk8cy/) saying

> If you want to format the output specifically for dbg(), specialize dbg_macro::prettyPrint

If this is officially supported, can you add it to README? And if not, have some alternative?

**Comment by sharkdp** [comment]
This is still possible, but the name has changed. You can specialize `dbg::pretty_print(std::ostream&, const T&)`. Here is the builtin example for `char`:
```c++
inline bool pretty_print(std::ostream& stream, const char& value) {
  const bool printable = value >= 0x20 && value <= 0x7E;

  if (printable) {
    stream << "'" << value << "'";
  } else {
    stream << "'\\x" << std::setw(2) << std::setfill('0') << std::hex
           << std::uppercase << (0xFF & value) << "'";
  }
  return true;
}
```

The Boolean return value determines whether or not the expression and the type name should be printed as well.



> add it to README

Sounds good!

**Comment by alexeyr** [comment]
Actually does it need to be in `namespace dbg` or can ADL let you use `pretty_print` in your own namespace?

**Comment by sharkdp** [comment]
I haven't checked, but I'd be fine with a change to use ADL to enable non-dbg-namespace usage.

**Comment by nocoinman** [comment]
Is there any reason one should prefer specializing `pretty_print` over `operator<<` for user defined datatypes? The latter seems already documented.

**Comment by sharkdp** [comment]
`operator<<` on `ostream` might already be implemented for some types (for other use cases). specializing `pretty_print` might be needed in those cases. But yeah, I haven't seen any need for this so far, so I'm fine with closing this for now. @alexeyr please report back if you think this should still be resolved.

**Comment by alexeyr** [comment]
I don't need it currently. But the point would be to use it when you want different output than `operator<<`, similarly to Rust's `Debug` ("should format the output in a programmer-facing, debugging context" vs `Display` ("for user-facing output").

**Comment by alexeyr** [comment]
I don't actually remember why exactly I wanted it originally, I think for something like `std::vector<our_type>` where we wouldn't want to change the behavior everywhere.
